/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DigestRouteImport } from './routes/digest'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimelineIdRouteImport } from './routes/timeline.$id'
import { Route as ArticleIdRouteImport } from './routes/article.$id'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestRoute = DigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineIdRoute = TimelineIdRouteImport.update({
  id: '/timeline/$id',
  path: '/timeline/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/digest': typeof DigestRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/article/$id': typeof ArticleIdRoute
  '/timeline/$id': typeof TimelineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/digest': typeof DigestRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/article/$id': typeof ArticleIdRoute
  '/timeline/$id': typeof TimelineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/digest': typeof DigestRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/article/$id': typeof ArticleIdRoute
  '/timeline/$id': typeof TimelineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/digest'
    | '/profile'
    | '/saved'
    | '/article/$id'
    | '/timeline/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/digest'
    | '/profile'
    | '/saved'
    | '/article/$id'
    | '/timeline/$id'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/digest'
    | '/profile'
    | '/saved'
    | '/article/$id'
    | '/timeline/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  DigestRoute: typeof DigestRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  ArticleIdRoute: typeof ArticleIdRoute
  TimelineIdRoute: typeof TimelineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest': {
      id: '/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof DigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/$id': {
      id: '/timeline/$id'
      path: '/timeline/$id'
      fullPath: '/timeline/$id'
      preLoaderRoute: typeof TimelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  DigestRoute: DigestRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  ArticleIdRoute: ArticleIdRoute,
  TimelineIdRoute: TimelineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
