/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as FollowingRouteImport } from './routes/following'
import { Route as DigestRouteImport } from './routes/digest'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TimelineIdRouteImport } from './routes/timeline.$id'
import { Route as JournalistIdRouteImport } from './routes/journalist.$id'
import { Route as ArticleIdRouteImport } from './routes/article.$id'

const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowingRoute = FollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => rootRouteImport,
} as any)
const DigestRoute = DigestRouteImport.update({
  id: '/digest',
  path: '/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineIdRoute = TimelineIdRouteImport.update({
  id: '/timeline/$id',
  path: '/timeline/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalistIdRoute = JournalistIdRouteImport.update({
  id: '/journalist/$id',
  path: '/journalist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleIdRoute = ArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/digest': typeof DigestRoute
  '/following': typeof FollowingRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/stories': typeof StoriesRoute
  '/article/$id': typeof ArticleIdRoute
  '/journalist/$id': typeof JournalistIdRoute
  '/timeline/$id': typeof TimelineIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/digest': typeof DigestRoute
  '/following': typeof FollowingRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/stories': typeof StoriesRoute
  '/article/$id': typeof ArticleIdRoute
  '/journalist/$id': typeof JournalistIdRoute
  '/timeline/$id': typeof TimelineIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/digest': typeof DigestRoute
  '/following': typeof FollowingRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/stories': typeof StoriesRoute
  '/article/$id': typeof ArticleIdRoute
  '/journalist/$id': typeof JournalistIdRoute
  '/timeline/$id': typeof TimelineIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/digest'
    | '/following'
    | '/profile'
    | '/saved'
    | '/stories'
    | '/article/$id'
    | '/journalist/$id'
    | '/timeline/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/digest'
    | '/following'
    | '/profile'
    | '/saved'
    | '/stories'
    | '/article/$id'
    | '/journalist/$id'
    | '/timeline/$id'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/digest'
    | '/following'
    | '/profile'
    | '/saved'
    | '/stories'
    | '/article/$id'
    | '/journalist/$id'
    | '/timeline/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  DigestRoute: typeof DigestRoute
  FollowingRoute: typeof FollowingRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  StoriesRoute: typeof StoriesRoute
  ArticleIdRoute: typeof ArticleIdRoute
  JournalistIdRoute: typeof JournalistIdRoute
  TimelineIdRoute: typeof TimelineIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/following': {
      id: '/following'
      path: '/following'
      fullPath: '/following'
      preLoaderRoute: typeof FollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digest': {
      id: '/digest'
      path: '/digest'
      fullPath: '/digest'
      preLoaderRoute: typeof DigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline/$id': {
      id: '/timeline/$id'
      path: '/timeline/$id'
      fullPath: '/timeline/$id'
      preLoaderRoute: typeof TimelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journalist/$id': {
      id: '/journalist/$id'
      path: '/journalist/$id'
      fullPath: '/journalist/$id'
      preLoaderRoute: typeof JournalistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$id': {
      id: '/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof ArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  DigestRoute: DigestRoute,
  FollowingRoute: FollowingRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  StoriesRoute: StoriesRoute,
  ArticleIdRoute: ArticleIdRoute,
  JournalistIdRoute: JournalistIdRoute,
  TimelineIdRoute: TimelineIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
